universe = vanilla
log = hello-chtc_$(Cluster).log
error = hello-chtc_$(Cluster)_$(Process).err

executable = chtc_datacl.sh
arguments = $(Process)
output = hello-chtc_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/pli72/628-2/comment.csv, data_cleaning_filter1.py, /home/pli72/628-2/home/anaconda3.tar.gz,/home/pli72/nltk_data/corpora/stopwords.tar.gz

request_cpus = 1
request_memory = 3GB
request_disk = 2GB

queue 1
