universe = vanilla
log = hello-chtc_$(Cluster).log
error = hello-chtc_$(Cluster)_$(Process).err

executable = runText.sh
arguments = $(Process)
output = hello-chtc_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = get_text.py, train_data.csv, testval_data.csv, anaconda3.tar.gz

request_cpus = 1
request_memory = 10GB
request_disk = 10GB

queue 1
