universe = vanilla
log = hello-chtc_$(Cluster).log
error = hello-chtc_$(Cluster)_$(Process).err

executable = run.sh
arguments = $(Process)
output = hello-chtc_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = doc2vec_model.py, process_text.py, train_data.csv, testval_data.csv, /home/yluo82/anaconda3.tar.gz

request_cpus = 4
request_memory = 50GB
request_disk = 100GB

queue 1
